version: '3.8'

services:
  # client:

  backend:
    image: tassianna/restaurant-app-3-tier:backend
    container_name: backend
    ports:
      - 6001:6001
    networks: 
      - mono
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - mono
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}


networks:
  mono:
    driver: bridge