version: '3.8'

services:
  client:
    image: disgraceful/restaurant-app-mono:client
    container_name: client
    ports:
    - 5173:5173
    networks:
    - mono

  # backend:

networks:
  mono:
    driver: bridge