version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - mono
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flor_de_sal"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    image: disgraceful/restaurant-app-mono:client-build
    container_name: client
    ports:
    - 5173:5173
    networks:
    - mono

  backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: tassianna/restaurant-app-3-tier:backend-start
    container_name: backend
    ports:
      - 6001:6001
    networks: 
      - mono
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres
      - DB_PORT=5432


networks:
  mono:
    driver: bridge