apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tassianna/restaurant-app-3-tier:backend-postgres
        ports:
        - containerPort: 6001
        resources:
            limits:
              memory: "512M"
              cpu: "500m"
        env:
        - name: SECRET
          value: "MySecret1!"

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database_url
              name: mysecret

        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              key: be_cloud_name
              name: mysecret

        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              key: be_cloud_api_key
              name: mysecret

        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              key: be_cloud_api_secret
              name: mysecret

        - name: PORT
          value: "6001"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 6001
    targetPort: 6001

