apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tassianna/restaurant-app-3-tier:backend-postgres
        ports:
        - containerPort: 6001
        env:
        - name: SECRET
          value: "MySecret1!"
        - name: DATABASE_URL
          value: "postgres://admin:Password123@postgres:5432/flor_de_sal"
        - name: CLOUD_NAME
          value: "drsjloigq"
        - name: CLOUD_API_KEY
          value: "926793658896175"
        - name: CLOUD_API_SECRET
          value: "5QhoDhOiODpETRSYUrRYDzu5tv0"
        - name: PORT
          value: "6001"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 6001
    targetPort: 6001

