apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-first
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres-service; sleep 2; done;']
      containers:
      - name: backend
        image: tassianna/restaurant-app-3-tier:backend-start
        ports:
        - containerPort: 6001
        resources:
          limits:
            memory: "512M"
            cpu: "500m"
        env:
        - name: SECRET
          value: "MySecret1!"

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: mysecret

        - name: CLOUD_NAME
          value: drsjloigq

        - name: CLOUD_API_KEY
          value: "926793658896175"

        - name: CLOUD_API_SECRET
          value: "5QhoDhOiODpETRSYUrRYDzu5tv0"

        - name: PORT
          value: "6001"

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: mysecret

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret

        - name: POSTGRES_DB
          value: flor_de_sal

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 6001
    targetPort: 6001

