apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
      - name: client-container
        image: tassianna/restaurant-app-3-tier:client-actions-deploy
        resources:
          limits:
            memory: "512M"
            cpu: "500m"
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: client-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: client-pod
  ports:
  - port: 5173
    targetPort: 5173

