apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9hZG1pbjpQYXNzd29yZDEyM0Bwb3N0Z3Jlcy0wLnBvc3RncmVzLXNlcnZpY2U6NTQzMi9mbG9yX2RlX3NhbA==
  postgres-password: UGFzc3dvcmQxMjM=
  postgres-user: YWRtaW4=
  
