apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9hZG1pbjpQYXNzd29yZDEyM0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZmxvcl9kZV9zYWw=
  postgres-password: UGFzc3dvcmQxMjM=
  postgres-user: YWRtaW4=
  
