apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:

      initContainers:
      - name: init-permissions
        image: postgres:latest
        command: ["sh", "-c"]
        args:
        - |
          chown -R 999:999 /var/lib/postgresql/data
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
          subPath: postgres

      containers:
      - name: postgres
        image: postgres:latest
        # Set the security context for the main container
        securityContext:
          runAsUser: 999 # Matches the 'postgres' user in the official image

        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              if [ "$(POD_NAME)" = "postgres-0" ]; then
                psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c "SELECT 1;"
              else
                psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c "SELECT * FROM pg_stat_replication;"
              fi
          initialDelaySeconds: 15
          periodSeconds: 10

        command:
        - sh
        - -c
        - |
          # Check if data directory is initialized
          if [ "$(POD_NAME)" = "postgres-0" ]; then
            if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then
              echo "Initializing database..."
              initdb -D /var/lib/postgresql/data
            fi
          fi

          # Start PostgreSQL in the foreground
          echo "Starting PostgreSQL..."
          pg_ctl -D /var/lib/postgresql/data -o "-c listen_addresses='*'" -w start

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
          subPath: postgres

        env:
        #- name: PGDATA
        #  value: /var/lib/postgresql/data

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: mysecret

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret

        - name: POSTGRES_DB
          value: flor_de_sal

        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: POSTGRES_REPLICATION_USER
          value: "replicator"

        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret

  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc-csi
      resources:
        requests:
          storage: 20Gi
