apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: init-replica
        image: postgres:latest
        command:
          - /bin/sh
          - -c
          - |
            if [ "$(hostname)" != "postgres-0" ]; then
              PGPASSWORD=$POSTGRES_PASSWORD pg_basebackup -h postgres-0.postgres-service -D /var/lib/postgresql/data -U replicator -Fp -Xs -P -R
            else
              psql -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '$POSTGRES_PASSWORD';"
              
              # Update postgresql.conf
              echo "wal_level = replica" >> /var/lib/postgresql/data/postgresql.conf
              echo "max_wal_senders = 3" >> /var/lib/postgresql/data/postgresql.conf
              echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
              
              # Update pg_hba.conf
              echo "host replication replicator 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
              
              # Restart PostgreSQL
              su - postgres -c "/usr/lib/postgresql/17/bin/pg_ctl -D /var/lib/postgresql/data restart"
            fi
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: postgres-password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: new-postgres-persistent-storage
            subPath: postgres
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: new-postgres-persistent-storage
          subPath: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: mysecret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret
        - name: POSTGRES_DB
          value: flor_de_sal
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_REPLICATION_USER
          value: "replicator"
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret

        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - admin
            - -d
            - flor_de_sal
            - -c
            - "SELECT 1;"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5

  volumeClaimTemplates:
  - metadata:
      name: new-postgres-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc-csi
      resources:
        requests:
          storage: 20Gi


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
