apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              if [ "$(POD_NAME)" = "postgres-0" ]; then
                # Master readiness check
                psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c "SELECT 1;"
              else
                # Replica readiness check
                psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c "SELECT * FROM pg_stat_replication;"
              fi
          initialDelaySeconds: 15
          periodSeconds: 10

        # Start-up commands
        command:
        - sh
        - -c
        - |
          if [ "$(POD_NAME)" = "postgres-0" ]; then
            # Initialize as master
            pg_ctl -D /var/lib/postgresql/data -o "-c listen_addresses='*'" -w start
          else
            # Initialize as replica
            until pg_basebackup -h postgres-0.postgres-service -D /var/lib/postgresql/data -U $(POSTGRES_REPLICATION_USER) -vP -W; do
              echo "Waiting for master to be ready..."
              sleep 5
            done
            pg_ctl -D /var/lib/postgresql/data -o "-c listen_addresses='*'" -w start
          fi
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
          subPath: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: mysecret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret
        - name: POSTGRES_DB
          value: flor_de_sal

        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_REPLICATION_USER
          value: "replicator" # Explicitly set replication user
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-replication-password
              name: mysecret

  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc-csi
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None #this makes it a headless service
