apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # securityContext:
      #   fsGroup: 1000
      # initContainers:
      # - name: init-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 1000:1000 /var/lib/postgresql/data"]
      #   volumeMounts:
      #   - name: postgres-persistent-storage
      #     mountPath: /var/lib/postgresql/data

      containers:
      - name: postgres
        image: postgres:latest
        #securityContext:
        #  runAsUser: 1000 # Matches the 'postgres' user in the official image
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: new-postgres-persistent-storage
          subPath: postgres

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: mysecret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret
        - name: POSTGRES_DB
          value: flor_de_sal
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_REPLICATION_USER
          value: "replicator"
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: mysecret

        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - admin
            - -d
            - flor_de_sal
            - -c
            - "SELECT 1;"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5

  volumeClaimTemplates:
  - metadata:
      name: new-postgres-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc-csi
      resources:
        requests:
          storage: 20Gi


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
