name: Build Workflow

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: checkout app
        uses: actions/checkout@v4

      - name: Setup Node.js for Applications
        uses: actions/setup-node@v3
        with: 
          node-version: '16-slim'

      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Client
        run: npm run build
        working-directory: ./client

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./backend

      - name: Build Backend
        run: npm run start
        working-directory: ./backend

  test:
    runs-on: ubuntu
    needs: build
    steps:
      - name: checkout app
        uses: actions/checkout@v4

      - name: Setup Node.js for Applications
        uses: actions/setup-node@v3
        with: 
          node-version: '16-slim'

      - name: Run Tests for Client
        run: npm run test
        working-directory: ./frontend

      - name: Run Tests for Backend
        run: npm run test
        working-directory: ./backend

  # dockerize:
  #   runs-on: ubuntu
  #   needs: test
  #   steps:

  # push:
  #   runs-on: ubuntu
  #   needs: dockerize
  #   steps:

  # deploy:
  #   runs-on: ubuntu
  #   needs: push
  #   steps:
